name: u_app_utils
description: Набор инструментов для приложений ЮНЭКТ
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  audioplayers: ^6.5.0
  barcode_widget: ^2.0.4
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  collection: ^1.17.1
  device_info_plus: ^12.2.0
  dio: ^5.8.0
  easy_refresh: ^3.4.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  flutter_cache_manager: ^3.4.1
  flutter_datawedge: ^3.2.0
  flutter_image_compress: ^2.4.0
  flutter_secure_storage: ^10.0.0
  fk_user_agent:
    git:
      url: git@github.com:kennir/fk_user_agent.git
      ref: '6068ac8'
  intl: ^0.20.2
  keyboard_actions: ^4.2.0
  mobile_scanner: ^7.0.1
  package_info_plus: ^8.1.3
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  sentry_flutter: ^9.7.0
  shared_preferences: ^2.5.1
  stack_trace: ^1.12.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  vibration: ^3.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/beep.mp3
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: ru.unact.u_app_utils
        pluginClass: UAppUtilsPlugin
      ios:
        pluginClass: UAppUtilsPlugin
